### ISSUE TITLE
ERR_EMPTY_RESPONSE using the GUI with Docker

### ISSUE THREAD

**Issue by gremo** [rclone/rclone#3927]
Any clue? Opening http://127.0.0.1:5572 gives me an ERR_EMPTY_RESPONSE.

```yml
version: '3.7'

services:
    rclone:
        image: 'rclone/rclone:latest'
        container_name: rclone
        ports:
            - 5572:5572
        volumes:
            - ./config/rclone:/config/rclone
            - ./data:/data
        command: "rcd --rc-web-gui --rc-web-gui-no-open-browser"
```
