### ISSUE TITLE
How the Docker image should be used?

### ISSUE THREAD

**Issue by gremo** [rclone/rclone#3935]
Right now, the official Docker image entrypoint is just `rclone` command. As a result, the container will start and immediately stop, making it quite "useless".

An example (in `docker-composer.yml` file):

```yml
version: '3.7'
services:
    # other services...
    backup:
        image: rclone/rclone
        volumes:
            - './config/rclone.conf:/config/rclone/rclone.conf'
            - './data:/data'
            - './log:/var/log:delegated'
        environment:
            TZ: Europe/Rome
```

Even if you change the entrypoint to something like `entrypoint: 'rclone sync /data remote:data'` it will still... do its job and the exiting.

I think this Docker image is usefull to run:

1. Calling `docker exec` for a manual sync or backup or restore: this is not possible because the **container is stopped**
2. Calling the _rclone_ command from another container in a scheduled way (using [ofelia](https://hub.docker.com/r/willfarrell/ofelia) for example): again, not possible because the **container is stopped**

As a workaround, I've found than I can override the `entrypoint: ['tail', '-f', '/dev/null']` but it seems... not right. Any idea? Thoughts?
