### ISSUE TITLE
Error reading available plugins when running as a user without a home directory

### ISSUE THREAD

**Issue by mmazerolle** [rclone/rclone#4592]
#### What is the problem you are having with rclone?

When running rclone as a user without a home directory, the first line reports an error trying to load plugins.
Example:
```
pi@quasar:~ $ sudo -u rclone rclone lsd --config /etc/rclone/rclone.conf Dropbox:
2020/09/14 12:33:40 ERROR : error reading available plugins: Error creating : /home/rclone/.cache/rclone/webgui/plugins/config
```

In this case, "rclone" is a user without password or home directory, who will issue rclone commands using the configuration file passed on the command line (in a cron job, for example).

#### What is your rclone version (output from `rclone version`)
rclone v1.53.1
- os/arch: linux/arm
- go version: go1.15

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Raspbian

####  Which cloud storage system are you using? (eg Google Drive)
Dropbox

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`sudo -u rclone rclone lsd --config /etc/rclone/rclone.conf Dropbox:`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2020/09/14 13:52:55 ERROR : error reading available plugins: Error creating : ```
/home/rclone/.cache/rclone/webgui/plugins/config
2020/09/14 13:52:55 DEBUG : rclone: Version "v1.53.1" starting with parameters ["rclone" "lsd" "-vv" "--config" "/etc/rclone/rclone.conf" "Dropbox:"]
2020/09/14 13:52:55 DEBUG : Using config file from "/etc/rclone/rclone.conf"
2020/09/14 13:52:55 DEBUG : Creating backend with remote "Dropbox:"
[correct listing of Dropbox]
2020/09/14 13:52:56 DEBUG : 3 go routines active
```

**Comment by mmazerolle** [comment]
Expectation is that rclone does not generate ERROR log entries for default behaviour when passed well-formed config files.

**Comment by ncw** [comment]
Yes that looks like a bug.

We shouldn't be reading anything about the plugins if we haven't initialized the webgui.

@negative0 ?

**Comment by negative0** [comment]
On it!

**Comment by minhphuc429** [comment]
had the same issue

**Comment by doob187** [comment]
here the same
```
2020/09/21 22:19:16 ERROR : error reading available plugins: Error creating : /root/.cache/rclone/webgui/plugins/config
```
docker based rclone install 
bash-5.0# rclone --version
rclone v1.53.1
- os/arch: linux/amd64
- go version: go1.15

installed as root per Docker Image
rclone commands running as abc UID 1000 User

**Comment by vviikk** [comment]
Any workaround this before it gets merged? Thanks.

**Comment by alias86** [comment]
Anyone got a working work around?

**Comment by enniosousa** [comment]
I downgraded to 1.50.2 on docker and it's okay now

**Comment by minhphuc429** [comment]
> I downgraded to 1.50.2 on docker and it's okay now

okay, we can use this for the moment. It work
```yaml
version: "3.7"
services:
  rclone:
    container_name: rclone
    image: rclone/rclone:1.50.2
    network_mode: host
    user: "${PUID}:${PGID}"
    volumes:
      - ./docker/config/rclone:/config/rclone
      - ./docker/data/rclone:/data:shared
      - ./docker/data/cache/rclone:/var/cache/rclone:shared
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    command: "mount gcrypt: /data/mount --allow-non-empty --dir-cache-time 1000h --poll-interval 15s --umask 002 --cache-dir=/var/cache/rclone --vfs-cache-mode full --vfs-cache-max-size 320G --vfs-cache-max-age 336h --rc --rc-web-gui --rc-user=${RC_USER} --rc-pass=${RC_PASS} --rc-addr :5572"
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
```
