### ISSUE TITLE
Problem copying files from AWS S3 with IAM auth on EKS

### ISSUE THREAD

**Issue by RafalSkolasinski** [rclone/rclone#5137]
#### What is the problem you are having with rclone?

Following from [forum](https://forum.rclone.org/t/question-on-aws-eks-and-iam/22841) and as per @ncw advice opening the issue here. After running the `copy` command (bellow) rclone just hangs without returning or communicating any error message that would help to identify the issue.

#### What is your rclone version (output from `rclone version`)

```
v1.54.0
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

official rclone image: `rclone/rclone:latest` (v1.54.0)

####  Which cloud storage system are you using? (e.g. Google Drive)

AWS S3 with IAM roles

Trying to copy data from S3 bucket authenticating with IAM role. Testing in following pod on EKS cluster
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: seldon-rclone-secret
type: Opaque
stringData:
  RCLONE_CONFIG_S3_TYPE: s3
  RCLONE_CONFIG_S3_PROVIDER: aws
  RCLONE_CONFIG_S3_ACCESS_KEY_ID: ""
  RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: ""
  RCLONE_CONFIG_S3_ENV_AUTH: "true"
---
apiVersion: v1
kind: Pod
metadata:
  name: rclone-pod
spec:
  containers:
  - name: rclone
    image: rclone/rclone:latest
    command: [ "/bin/sh", "-c", "--", "sleep 3600"]
    envFrom:
    - secretRef:
        name: seldon-rclone-secret
```

after exec-ing into it
```
kubectl exec -it rclone-pod -- sh
```
and trying below commands. 

The s3 bucket in question has `s3:*` permissions set for this subdirectory and 
```
aws s3 cp s3://<bucket name redacted>/product/env/test ./test
``` 
is confirmed to work directly from the k8s node.

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
rclone copy s3:<bucket name redacted>/product/env/test .
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
/data # rclone copy s3:<bucket name redacted>/product/env/test . -vvv
2021/03/17 14:19:32 DEBUG : rclone: Version “v1.54.0” starting with parameters [“rclone” “copy” “s3:<bucket name redacted>/product/env/test” “.” “-vvv”]
2021/03/17 14:19:32 DEBUG : Creating backend with remote “s3:<bucket name redacted>/product/env/test”
2021/03/17 14:19:32 NOTICE: Config file “/config/rclone/rclone.conf” not found - using defaults
```
