### ISSUE TITLE
Docker Volume Plugin has broken umask handling

### ISSUE THREAD

**Issue by jag426** [rclone/rclone#5617]
I am using the docker volume plugin v1.56.1 to mount a google drive remote in a docker container. I'm using the following settings for the volume:
```
volumes:
        gdrive_borg:
                driver: rclone:v1.56.1
                driver_opts:
                        remote: "gdrive-borg:"
                        uid: "666"
                        gid: "666"
                        umask: "0007"
                        allow_other: "true"
                        default_permissions: "true"
                        no_modtime: "true"
                        max_read_ahead: 16M
                        vfs_cache_max_size: 1G
                        vfs_cache_mode: full
```
This volume is mounted to /data in the container.

I noticed that when changing the umask's group digit to something other than 0, the permissions for the mount point in the container are wrong. Here's a table of the ones I tried:

```
umask   expected        actual
0000    drwxrwxrwx      drwxrwxrwx

0001    drwxrwxrw-      drwxrwxrw-
0002    drwxrwxr-x      drwxrwxr-x
0003    drwxrwxr--      drwxrwxr--
0004    drwxrwx-wx      drwxrwx-wx
0005    drwxrwx-w-      drwxrwx-w-
0006    drwxrwx--x      drwxrwx--x
0007    drwxrwx---      drwxrwx---

0010    drwxrw-rwx      drwxrw-r-x
0020    drwxr-xrwx      drwxr-x-wx
0030    drwxr--rwx      drwxr----x
0040    drwx-wxrwx      drwx-w-rwx
0050    drwx-w-rwx      drwx--xr-x
0060    drwx--xrwx      drwx----wx
0070    drwx---rwx      drw-rwx--x

0017    drwxrw----      drwxr-xrw-
0027    drwxr-x---      drwxr--r--
0037    drwxr-----      drwx-wx-w-
0047    drwx-wx---      drwx-w----
0057    drwx-w----      drwx---rw-
0067    drwx--x---      drw-rwxr--
0077    drwx------      drw-rw--w-
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.
