### ISSUE TITLE
Rclone with Kubernetes - Fuse volume problem

### ISSUE THREAD

**Issue by marc-cenon** [rclone/rclone#5637]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/using-rclone-with-kubernetes/26721

#### What is the problem you are having with rclone?

Unable to expose my google drive to the host
My google drive is mounted correctly in the container but the volume on the host is empty.

#### What is your rclone version (output from `rclone version`)

rclone --version
rclone v1.56.1

os/version: alpine 3.14.2 (64 bit)
os/kernel: 5.4.0-1042-raspi (aarch64)
os/type: linux
os/arch: arm64
go/version: go1.17.1
go/linking: static
go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-1042-raspi aarch64) with Kubernetes k8S

kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/arm64"}

Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/arm64"}

#### Which cloud storage system are you using? (e.g. Google Drive)

Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

no command in special....
I tried to expose my google drive as as volume on my NFS server. Here is my deployment file

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rclone
  name: rclone
  namespace: rclone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rclone
  template:
    metadata:
      labels:
        app: rclone
      annotations:
        container.apparmor.security.beta.kubernetes.io/rclone: localhost/fuse
    spec:
      serviceAccountName: default
      volumes:
      - name: share-data
        emptyDir: {}
      - name: rclone-data
        hostPath:
          path: /mnt/nfs/kubernetes/rclone/data
      - name: rclone-conf
        hostPath:
          path: /mnt/nfs/kubernetes/rclone/conf
      - name: rclone-passwd
        hostPath:
          path: /etc/passwd
      - name: rclone-group
        hostPath:
          path: /etc/group
      containers:
      - image: rclone/rclone:1.56
        name: rclone
        command: ["rclone"]
        args: ["mount", "google-drive:", "/data", "--allow-root", "--allow-other"]
        resources:
          limits:
            smarter-devices/fuse: 1
            memory: 512Mi
          requests:
            smarter-devices/fuse: 1
            cpu: 100m
            memory: 256Mi
        ports:
        - containerPort: 5572
          name: webui
          protocol: TCP
        volumeMounts:
        - name: rclone-data
          mountPath: /data
        - name: rclone-group
          mountPath: /etc/group
          readOnly: true
        - name: rclone-passwd
          mountPath: /etc/passwd
          readOnly: true
        - name: rclone-conf
          mountPath: /config/rclone
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "SETPCAP", "MKNOD"]
      nodeSelector:
        name: sys
```
