### ISSUE TITLE
Unsupported backend options in docker volume plugin

### ISSUE THREAD

**Issue by madhavtummala** [rclone/rclone#5898]
#### What is the problem you are having with rclone?
rclone docker volume plugin doesn't support all options

#### What is your rclone version (output from `rclone version`)
rclone v1.57.0
- os/version: raspbian 11.1 (64 bit)
- os/kernel: 5.10.63-v8+ (aarch64)
- os/type: linux
- os/arch: arm64
- go/version: go1.17.2
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Ubuntu Server 21.04, arm64

#### Which cloud storage system are you using? (e.g. Google Drive)
Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
docker volume specification in docker-compose
```
volumes:
  movies:
    driver: rclone
    driver_opts:
      remote: 'landsraad:MOVIES'
      dir-cache-time: 30m
      vfs-cache-mode: full
      cache-dir: /mnt/volume/cache1
      vfs-cache-max-size: 1000G
      vfs-write-back: 30m
      vfs-cache-max-age: 720h
      allow-other: 'true'
      log-level: INFO
      log-file: /home/ubuntu/dune/config/rclone/movies.log
      allow-non-empty: 'true'
      vfs-read-ahead: 256M
      uid: ${PUID}
      gid: ${PGID}
      attr-timeout: 1m
```

#### A logs from docker-compose up -d command
```
ERROR: create dune_movies: VolumeDriver.Create: unsupported backend option "cache-dir"
```
```
ERROR: create dune_movies: VolumeDriver.Create: unsupported backend option "log-file"
```

Can we not specify these options in driver opts for the volume?  
Is there a one-on-one mapping from env variables / rclone options to this plugin options ?
