### ISSUE TITLE
[WEBUI] Does not include x-expected-entity-length when moving big files

### ISSUE THREAD

**Issue by greatbody** [rclone/rclone#6119]
#### What is the problem you are having with rclone?
When I move an large file from one WebDAV source to the same WebDAV but to different path, the x-expected-entity-length does not appear in the request.

#### What is your rclone version (output from `rclone version`)

V1.58.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

This is not OS related issue.

#### Which cloud storage system are you using? (e.g. Google Drive)

WebDAV

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rcd --rc-web-gui --rc-addr :5572 --rc-user xxx --rc-pass xxx

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

.....

2022/04/22 03:09:14 ERROR : somefolder/somezip.zip: Failed to copy: Copy NewObject failed: object not found

....

But I see from the WebDAV server that the request it received has the following headers:

request: host = 10.10.10.57:8085
request: user-agent = rclone/v1.58.0
request: authorization = Basic YWR=
request: destination = http://10.10.10.57:8085/abc.zip
request: overwrite = F
request: referer = http://10.10.10.57:8085/
request: accept-encoding = gzip

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
> When I move an large file from one WebDAV source to the same WebDAV but to different path, the x-expected-entity-length does not appear in the request.

What is the `x-expected-entity-length` header? I've not heard of that one before. Can you point to some docs?

Which WebDAV server are you using?

**Comment by greatbody** [comment]
Refer: 
https://www.javadoc.io/doc/org.cryptomator/webdav-nio-adapter/0.2.2/org/cryptomator/frontend/webdav/servlet/package-summary.html

https://lists.w3.org/Archives/Public/ietf-http-wg/2008OctDec/0110.html

https://evertpot.com/260/

I cannot find it in webdav protocal but there is a issue when I move file with rclone, the content-length field is missing when the file is big and chunked.

Thanks, and please let me know if you need other info.

**Comment by greatbody** [comment]
Any update?

**Comment by ncw** [comment]
How do you know that `x-expected-entity-length` is the problem?

What is the simplest rclone comand you can do that demonstrates the problem?

Can you do it with `-vv --dump headers` and post the result?

**Comment by greatbody** [comment]
> How do you know that `x-expected-entity-length` is the problem?
> 
> What is the simplest rclone comand you can do that demonstrates the problem?
> 
> Can you do it with `-vv --dump headers` and post the result?

I am using docker version with WebUI, and my copy/move operation is performed by UI drag and drop, not sure how to do that `-vv --dump headers`, do you mean

```
version: "2.1"
services:
  rclone_rclone:
    image: rclone/rclone
    container_name: rclone_rclone
    restart: always
    command: rcd --rc-web-gui --rc-addr :5572 --rc-user xxx --rc-pass xxx -vv --dump headers
    ports:
      - "5572:5572"
    volumes:
      - /mnt/tvshow/rclone-data/config:/config/rclone
      - /mnt/tvshow/rclone-data/cache:/root/.cache/rclone
    environment:
      - PHP_TZ=Europe/London
      - PUID=1000
      - PGID=1000
```

Thank again for your kind reply.
