### ISSUE TITLE
Rclone attempts to move the config file when modifying it and that doesn't play nicely with Docker

### ISSUE THREAD

**Issue by aradalvand** [rclone/rclone#6656]
I'm trying to use Rclone with Docker (and Docker Compose), I have the following (very simple) `compose.yaml`, there's also an `rclone.conf` file in the same directory, the contents of which aren't terribly relevant, it just contains the usual Google Drive configurations:

```yaml
volumes:
  postgres-backups:

services:
  postgres:
    image: postgres:15.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-backups:/backups
    # Blah blah blah...

  rclone:
    image: rclone/rclone:1.61.1
    container_name: rclone
    volumes:
      - postgres-backups:/postgres-backups:ro
      - ./rclone.conf:/rclone.conf:rw
    command: sync -v --config /rclone.conf /postgres-backups gdrive:/database-backups
```

Notice that the `rclone.conf` file is being mounted with a `rw` (read-write) flag, meaning that Rclone does have permission to actually modify it (and it will need to since it will have to refresh the token). But when running `docker compose up`, if the token has expired and Rclone has therefore refreshed it and then needs to modify the config file, I get the following output (notice the error):
```
2022/12/25 18:54:30 ERROR : Failed to save config after 10 tries: failed to move previous config to backup location: rename /rclone.conf /rclone.conf.old: device or resource busy
2022/12/25 18:54:32 INFO  : There was nothing to transfer
2022/12/25 18:54:32 INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Checks:                 2 / 2, 100%
Elapsed time:         6.8s
```
The error seems to be caused by the fact that Rclone is attempting to rename (i.e. move) the `rclone.conf` file, but Docker doesn't allow that, even with `rw` permissions.

If you go into the container and try to run `mv` manually, you'll get the same error:
```
# mv /rclone.conf /rclone.conf.old
mv: can't rename '/rclone.conf': Resource busy
```

This is kinda unintuitive and unexpected.

This problem would be circumvented entirely if Rclone instead **copied** the config file into a new location as a backup, instead of trying to **move** it; and then simply wrote to the original file. This wouldn't change the final result, but also wouldn't create issues in cases where the file isn't allowed to be moved.

What do you think?

#### What is your rclone version (output from `rclone version`)
rclone v1.61.1
- os/version: alpine 3.17.0 (64 bit)
- os/kernel: 5.10.16.3-microsoft-standard-WSL2 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.4
- go/linking: static
- go/tags: none
