### ISSUE TITLE
rclone volume plugin does not remount crypt volume on docker restart

### ISSUE THREAD

**Issue by logopk** [rclone/rclone#6769]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/docker-volume-gone-after-reboot/33082
while the solution presented there does not work for crypted remotes

#### What is the problem you are having with rclone?

upon restart none of my external crypted volumes are recreated and mounted, I have to recreate the volumes with docker-compose

thus my nextcloud fails, as the "external" volumes are not existing

#### What is your rclone version (output from `rclone version`)

v1.61.1

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Debian 11 64bit, docker v23.0.1

#### Which cloud storage system are you using? (e.g. Google Drive)

- webdav  (1&1)
- onedrive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

the docker volume plugin on restart

access is working fine after recreation of  the volumes and start of nextcloud, until the next restart!

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
journalctl --unit docker | grep rclone
Feb 16 11:08:51 docker2 dockerd[842]: time="2023-02-16T11:08:51+01:00" level=error msg="2023/02/16 10:08:51 NOTICE: Failed to restore volume \"rclone-mount_crypt\": cannot parse path \"\": can't use empty string as a path" plugin=90e43cf9c32a43c8428773e66501c25eef54984f88a42ff4886c796aec5bdfdd
Feb 16 11:08:51 docker2 dockerd[842]: time="2023-02-16T11:08:51+01:00" level=error msg="2023/02/16 10:08:51 NOTICE: Failed to restore volume \"rclone-mount_crypt_ms\": cannot parse path \"\": can't use empty string as a path" plugin=90e43cf9c32a43c8428773e66501c25eef54984f88a42ff4886c796aec5bdfdd
Feb 16 11:08:51 docker2 dockerd[842]: time="2023-02-16T11:08:51+01:00" level=error msg="2023/02/16 10:08:51 INFO  : Serving unix socket: /run/docker/plugins/rclone.sock" plugin=90e43cf9c32a43c8428773e66501c25eef54984f88a42ff4886c796aec5bdfdd
```

i feel that this is caused by the empty fs value in
https://github.com/rclone/rclone/blob/v1.61.1/cmd/serve/docker/options.go line 62ff
```
		case "remote", "fs":
			p, err := fspath.Parse(str)
			if err != nil || p.Name == ":" {
				return fmt.Errorf("cannot parse path %q: %w", str, err)
			}
```
```
cat /var/lib/docker-plugins/rclone/cache/docker-plugin.state | jq

[
  {
    "name": "rclone-mount_crypt",
    "mountpoint": "/mnt/rclone-mount_crypt",
    "created": "2023-02-15T23:25:49.345473169Z",
    "fs": "",
    "type": "crypt",
    "options": {
      "allow_other": "true",
      "crypt_password": "xxxx",
      "crypt_password2": "xxxx",
      "crypt_remote": "oneandone:/rclone",
      "poll_interval": "0"
    },
    "mounts": []
  },
  {
    "name": "rclone-mount_crypt_ms",
    "mountpoint": "/mnt/rclone-mount_crypt_ms",
    "created": "2023-02-15T23:25:50.225401832Z",
    "fs": "",
    "type": "crypt",
    "options": {
      "allow_other": "true",
      "crypt_password": "xxx",
      "crypt_password2": "xxxx",
      "crypt_remote": "onedrive:crypt",
      "poll_interval": "0"
    },
    "mounts": []
  }
]
```
Volumes are created by a separate docker-compose file like so:
```
volumes:
  crypt:
    driver: rclone:latest
    driver_opts:
      type: 'crypt'
      crypt_remote: 'oneandone:/rclone'
      crypt_password: 'xxxx'
      crypt_password2: 'xxxx'
      allow_other: 'true'
      poll_interval: 0
#      modules: 'iconv,from_code=UTF-16-MAC,to_code=UTF-8-MAC'
  crypt_ms:
    driver: rclone:latest
    driver_opts:
      type: 'crypt'
      crypt_remote: 'onedrive:crypt'
      crypt_password: 'xxxx'
      crypt_password2: 'xxxx'
      allow_other: 'true'
      poll_interval: 0
```

Thank you for looking into this.

Peter

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.
