### ISSUE TITLE
metrics: `rclone rc` binding metrics endpoint

### ISSUE THREAD

**Issue by hiddenmarten** [rclone/rclone#8248]
#### The associated forum post URL from `https://forum.rclone.org`
I don't have any, just wanted to create an issue to link my future PR with.

#### What is the problem you are having with rclone?
`rclone rc` trying to bind metrics endpoint if environment variable `RCLONE_METRICS_ADDR` is set

#### What is your rclone version (output from `rclone version`)
v1.68.2

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Linux 

#### Which cloud storage system are you using? (e.g. Google Drive)
Doesn't matter in that case.

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`RCLONE_METRICS_ADDR="0.0.0.0:9000" rclone rc -vv rc/noop`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

NOTE: `└──╼ $ RCLONE_METRICS_ADDR="0.0.0.0:9000" rclone rcd` was run in advance.

```
└──╼ $ RCLONE_METRICS_ADDR="0.0.0.0:9000" rclone rc -vv rc/noop
2024/12/15 22:21:21 DEBUG : Setting  metrics_addr="0.0.0.0:9000" from environment variable RCLONE_METRICS_ADDR
2024/12/15 22:21:21 DEBUG : Setting --metrics-addr "0.0.0.0:9000" from environment variable RCLONE_METRICS_ADDR="0.0.0.0:9000"
2024/12/15 22:21:21 DEBUG : rclone: Version "v1.68.2" starting with parameters ["rclone" "rc" "-vv" "rc/noop"]
2024/12/15 22:21:21 CRITICAL: Failed to start metrics server: failed to init server: listen tcp 0.0.0.0:9000: bind: address already in use
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by hiddenmarten** [comment]
_Duplicate explanation of use cases from PR for the sake of context:_

I encountered this issue when running rclone in Kubernetes. Let me provide a simplified Deployment manifest to explain the context:

```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: rclone
          image: rclone/rclone:1.68.2
          args:
            - rcd
          env:
            - name: RCLONE_METRICS_ADDR
              value: ":9000"
          livenessProbe:
            exec:
              command:
                - rclone rc rc/noop
```

In this setup, the liveness probe fails because the `rclone rc rc/noop` command does not work correctly when the `RCLONE_METRICS_ADDR` environment variable is set. 

As a workaround, we can modify the liveness probe command like this: `RCLONE_METRICS_ADDR="" rclone rc rc/noop`

However, this approach raises a concern: it's not immediately clear from the manifest why we are overriding the `RCLONE_METRICS_ADDR` variable. This lack of clarity could lead to confusion for others reading the configuration.

Another potential scenario to consider: If someone sets `RCLONE_METRICS_ADDR` globally in their `~/.bashrc` or `~/.zshrc` file, they may inadvertently prevent rclone from working correctly when running commands locally from the CLI.
