### ISSUE TITLE
Support bwlimit in docker volumes

### ISSUE THREAD

**Issue by jehon** [rclone/rclone#8401]
#### What is your current rclone version (output from `rclone version`)?

rclone v1.69.1
- os/version: ubuntu 24.04 (64 bit)
- os/kernel: 6.8.0-1018-raspi (aarch64)
- os/type: linux
- os/arch: arm64 (ARMv8 compatible)
- go/version: go1.24.0
- go/linking: static
- go/tags: none

#### What problem are you are trying to solve?

Limit bandwith in docker volume.
But bwlimit is not supported in docker volume parameters

#### How do you think rclone should be changed to solve that?

Add translation for bwlimit in the docker volume system

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by jehon** [comment]
The docker volume configuration I try to use:

```
volumes:
  cloud:
    # https://rclone.org/docker/#installing-as-managed-plugin
    driver: rclone
    driver_opts:
      remote: "cloud:"
      allow_other: "true"
      vfs_cache_mode: full
      poll_interval: 0
      bwlimit: 500K
```

The error message:

`Error response from daemon: create stack_cloud: VolumeDriver.Create: unsupported backend option "bw_limit"`

**Comment by kapitainsky** [comment]
Before posting please Google for answers first next time.

https://forum.rclone.org/t/docker-volume-plugin-bwlimit-timetable/28219

**Comment by ncw** [comment]
After 33d2747829e1f0e2aa0cb17da30d3f8500c811ad it occurred to me that it would be very easy to add **all** rclone global options to the docker plugin config file which would make users lives easier and workaround the docker plugin bug with spaces.

I've implemented that on this branch [fix-8401-docker-volume](https://github.com/rclone/rclone/tree/fix-8401-docker-volume) 

However you are going to have to build that yourself as we don't currently push betas or branches of the docker volume plugin.

You'll need to checkout the branch above then run `make docker-plugin-create` and it should build the plugin for you.

I'd be interested to know if it works - I haven't tried it!

**Comment by jehon** [comment]
Building it from scratch is a bit too much complex for my setup... But if you release on beta channel, I can add it to my docker and test it

(I do a rclone selfupdate --beta + docker restart and the new version should be running)

**Comment by yqs112358** [comment]
It seems that the latest published version of rclone-docker-plugin still does not suppot the `bwlimit` parameter.

docker-compose.yml:
```yaml
volumes:
  openlist-rclone:
    driver: rclone/docker-volume-rclone:amd64
    driver_opts:
      ...
      bwlimit: '1M:off'
```

Error:
```
[+] Running 1/1
 ✘ Volume mcsm_openlist-rclone  Error                                                                        0.0s 
Error response from daemon: create mcsm_openlist-rclone: VolumeDriver.Create: unsupported backend option "bwlimit"
```

Version:
```
❯ sudo docker plugin list
ID             NAME                                DESCRIPTION                       ENABLED
1598450f5c1f   rclone/docker-volume-rclone:amd64   Rclone volume plugin for Docker   true
```
( Installed this latest version at 2025-11-17)
